dubbo:
  application:
    name: dubbo-service
    id: dubbo-service
  provider:
    executes: 100
    retries: 0
    version: local
  consumer:
    cluster: failfast
    retries: 0
    check: false
  protocol:
    name: dubbo
  registry:
    address: zookeeper://localhost:2181
    simplified: true